replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 27017

environment:
  MONGO_INITDB_ROOT_USERNAME: your-username
  MONGO_INITDB_ROOT_PASSWORD: your-password
