# Use the official MongoDB image
FROM mongo:latest

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=test
ENV MONGO_INITDB_DATABASE=test

# Copy custom configuration files if needed
# COPY ./mongod.conf /etc/mongod.conf

# Expose the default MongoDB port
EXPOSE 27017

# CMD instruction allows you to set a default command to run when the container starts
CMD ["mongod"]